### ISSUE TITLE
Bad Request For request 'GET /' [Host not allowed: 127.0.0.1:9000]

### ISSUE THREAD

**Issue by josefmaxa** [playframework/play-java-starter-example#60]
Fresh downloaded example doesn't work (I'm using win 10 and latest chrome).

To make it work you have to modify application.conf:
(uncoment allowed and add "127.0.0.1")
hosts {
    # Allow requests to example.com, its subdomains, and localhost:9000.
    allowed = [".example.com", "localhost:9000", "127.0.0.1"]
  }

Quite a rough starter...

Log:
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] application - ApplicationTimer demo: Starting application at 2018-03-14T12:06:32.012Z
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    filters.ExampleFilter

[info] play.api.Play - Application started (Dev)
[warn] p.f.h.AllowedHostsFilter - Host not allowed: 127.0.0.1:9000

**Comment by marcospereira** [comment]
This was fixed by #61.
